name: CD | Docker-Build-Release

on:
  push:
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: false
        default: "dev"

jobs:
  docker-build:
    runs-on: Siguiente-build-runner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: siguiente/vllm-openai:latest

      - name: Inspect
        run: |
          docker image inspect siguiente/vllm-openai:latest