name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: vllm-openai:latest

      - name: Inspect
        run: |
          docker image inspect vllm-openai:latest